spring:
  application:
    name: mcplink

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  config:
    import: classpath:secret.yml

  datasource:
    jdbc-url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Seoul
    username: ${mysql.user}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  github:
    token: ${github.token}

  gemini:
    api-key: ${gemini.api-key}

mongodb:
  atlas:
    uri: mongodb+srv://${mongodb.atlas.username}:${mongodb.atlas.password}@${mongodb.atlas.cluster}.mongodb.net/?retryWrites=true&w=majority&appName=${mongodb.atlas.app-name}
    database: ${mongodb.atlas.database}

server:
  host: ${server.host}
  http2:
    enabled: true
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    tags-sorter: alpha

app:
  analysis:
    temp-dir: ${app.analysis.temp-dir}
    osv-scanner-cmd: ${app.analysis.osv-scanner-cmd}

ssafy:
  oauth:
    client-id: ${ssafy.oauth.client-id}
    client-secret: ${ssafy.oauth.client-secret}
    redirect-uri: ${ssafy.oauth.redirect-uri}
    authorization-uri: ${ssafy.oauth.authorization-uri}
    token-uri: ${ssafy.oauth.token-uri}
    user-info-uri: ${ssafy.oauth.user-info-uri}
    scope: ${ssafy.oauth.scope}

jwt:
  secret: ${jwt.secret}
  access-expiration: ${jwt.access-expiration}
  refresh-expiration: ${jwt.refresh-expiration}
  secure-path: ${jwt.secure-path}
  oauth-ssafy-path: ${jwt.oauth-ssafy-path}